// <auto-generated />
using CBV.Infra.Data.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace CBV.Infra.Data.Migrations
{
    [DbContext(typeof(CBVContext))]
    [Migration("20190624175447_Create_Venda_Item")]
    partial class Create_Venda_Item
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);


            modelBuilder.Entity("CBV.Core.Domain.Entities.Venda", v =>
            {
                v.Property<int>("VendaId")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                v.Property<decimal>("CashbackTotal");

                v.Property<decimal>("ValorTotal");

                v.Property<DateTime>("Data");

                v.HasKey("VendaId");

                v.ToTable("Venda");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.ItemVenda", i =>
            {
                i.Property<int>("ItemVendaId")
                       .ValueGeneratedOnAdd()
                       .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                i.Property<int>("DiscoId");

                i.Property<int>("VendaId");

                i.Property<int>("Quantidade");

                i.Property<decimal>("PrecoUnitario");

                i.Property<decimal>("ValorTotal");

                i.Property<decimal>("CashbackValor");

                i.Property<decimal>("CashbackPercentual");

                i.HasKey("ItemVendaId");

                i.ToTable("ItemVenda");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.Disco.ItemVenda", i =>
            {
                i.HasOne("CBV.Core.Domain.Entities.Disco", "Disco")
                    .WithMany("ItensVenda")
                    .HasForeignKey("IdDisco")
                    .OnDelete(DeleteBehavior.Cascade);

                i.HasOne("CBV.Core.Domain.Entities.Venda", "Venda")
                    .WithMany("ItensVenda")
                    .HasForeignKey("VendaId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

#pragma warning restore 612, 618
        }
    }
}
