// <auto-generated />
using CBV.Infra.Data.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace CBV.Infra.Data.Migrations
{
    [DbContext(typeof(CBVContext))]
    partial class CBVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);


            modelBuilder.Entity("CBV.Core.Domain.Entities.Cashback", c =>
            {
                c.Property<int>("CashbackId");

                c.Property<int>("DiaSemanaId");

                c.Property<int>("GeneroId");

                c.Property<decimal>("Percentual");

                c.HasKey("CashbackId");

                c.ToTable("Cashback");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.Venda", v =>
            {
                v.Property<int>("VendaId")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                v.Property<decimal>("CashbackTotal");

                v.Property<decimal>("ValorTotal");

                v.Property<DateTime>("Data");

                v.HasKey("VendaId");

                v.ToTable("Venda");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.ItemVenda", i =>
            {
                i.Property<int>("ItemVendaId")
                       .ValueGeneratedOnAdd()
                       .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                i.Property<int>("DiscoId");

                i.Property<int>("VendaId");

                i.Property<int>("Quantidade");

                i.Property<decimal>("PrecoUnitario");

                i.Property<decimal>("ValorTotal");

                i.Property<decimal>("CashbackValor");

                i.Property<decimal>("CashbackPercentual");

                i.HasKey("ItemVendaId");

                i.ToTable("ItemVenda");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.Disco", d =>
            {
                d.Property<int>("DiscoId")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                d.Property<string>("Artistas")
                    .IsRequired()
                    .HasMaxLength(150);

                d.Property<int>("GeneroId");

                d.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100);

                d.Property<decimal>("Preco");

                d.HasKey("DiscoId");

                d.ToTable("Disco");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.DiaSemana", d =>
            {
                d.Property<int>("DiaSemanaId");

                d.Property<string>("Nome")
                     .IsRequired()
                     .HasMaxLength(15);

                d.HasKey("DiaSemanaId");

                d.ToTable("DiaSemana");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.Genero", g =>
            {
                g.Property<int>("GeneroId");

                g.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(10);

                g.HasKey("GeneroId");

                g.ToTable("Genero");
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.Disco", d =>
            {
                d.HasOne("CBV.Core.Domain.Entities.Genero", "Genero")
                    .WithMany("Discos")
                    .HasForeignKey("GeneroId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("CBV.Core.Domain.Entities.Disco.ItemVenda", i =>
            {
                i.HasOne("CBV.Core.Domain.Entities.Disco", "Disco")
                    .WithMany("ItensVenda")
                    .HasForeignKey("IdDisco")
                    .OnDelete(DeleteBehavior.Cascade);

                i.HasOne("CBV.Core.Domain.Entities.Venda", "Venda")
                    .WithMany("ItensVenda")
                    .HasForeignKey("VendaId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

#pragma warning restore 612, 618
        }
    }
}
